### ISSUE TITLE
kaptTest not detected as kapt usage

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#776]
**Build scan link**
[](http://gradle.affirm-dev.com/s/3irzggszoazni)

**Plugin version**
1.13.1

**Gradle version**
7.5

**(Optional) Android Gradle Plugin (AGP) version**
7.2.1

**`reason` output for bugs relating to incorrect advice**
  Unused plugins that can be removed:
    kotlin-kapt: this project has the kotlin-kapt (org.jetbrains.kotlin.kapt) plugin applied, but there are no used annotation processors.

**Describe the bug**
I have a kaptTest dependency on Dagger. The plugin suggests KAPT removal.

**To Reproduce**
1) Add a kaptTest dependency on Dagger (com.google.dagger:dagger:2.42).
2) Run dependency analysis.

**Expected behavior**
When I have kaptTest dependencies then the plugin shouldn't suggest KAPT plugin removal.

**Comment by autonomousapps** [comment]
Hm, it's actually fairly unusually to see someone use `kaptTest`. I'm just checking, but do you mean `kaptAndroidTest`?

**Comment by bartek-wesolowski** [comment]
I mean `kaptTest`, but `kaptAndroidTest` might have similar problems.

**Comment by BenTilbrook** [comment]
> it's actually fairly unusually to see someone use kaptTest

`kaptTest` is [required for Hilt Android unit tests](https://dagger.dev/hilt/gradle-setup.html), so I think it is _very_ common.

**Comment by BenTilbrook** [comment]
Yes, Hilt is very common. It's one of, if not the most popular DI frameworks on Android.

**Comment by autonomousapps** [comment]
This may possibly be resolved with a recent merge to main. https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/804

Would you mind checking the snapshot? (wait at least a couple of hours)

**Comment by bartek-wesolowski** [comment]
I can check it, but please give me more time. I might be OOO until the end of this week.

**Comment by autonomousapps** [comment]
No problem. I said "wait at least a couple of hours" just in case you tried too early and didn't get the right snapshot. This has actually been released at this point and you can just use the latest version (1.14.1 at time of writing).

**Comment by bartek-wesolowski** [comment]
I checked it using 1.14.1. The problem still exists for me. I think https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/804 doesn't solve it because it adds support for analysing `androidTest` source sets (which is very nice BTW) and this problem is about regular unit tests.
Could anyone else test it too? I'm working on a big project and my issue might be with something else.

**Comment by autonomousapps** [comment]
Absent a reproducer, I'm going to remove this from the `next` milestone.
